In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3: 6]

array([4, 5, 6])

In [7]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy

In [12]:
b

array([4, 5, 6, 7])

In [13]:
b[0] = 444444666

In [14]:
b

array([444444666,         5,         6,         7])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [16]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [17]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [18]:
arr[arr>23]

array([54, 53, 34])