In [28]:
import numpy as np

In [29]:
# 1.Create a 3×3 array filled with random numbers
arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='float32') 
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [30]:
#print its shape.
arr.shape

(3, 3)

In [31]:
arr.dtype

dtype('float32')

In [32]:
#2. Convert an array of floats [1.1, 2.2, 3.3] into integers.
n = arr.astype('int32')
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [33]:
flat = n.flatten()

In [34]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [35]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [36]:
#3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr[[1,3,5]]

array([2, 4, 6])

In [37]:
#4. Reshape a 1D array of size 9 into a 3×3 matrix
flat.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [38]:
#5. Use boolean masking to filter numbers greater than 50 in an array.
new = np.array([10,20,30,40,50,60,70,90,100])
new

array([ 10,  20,  30,  40,  50,  60,  70,  90, 100])

In [39]:
new[new>50]

array([ 60,  70,  90, 100])